variables:
  IMAGE_NAME: claudiutulbure/public
  IMAGE_TAG: user-image
build:
  image: docker:20.10.16
  services:
   - docker:20.10.16-dind
  script:
   - docker build -t $IMAGE_NAME:$IMAGE_TAG .
   - docker push $IMAGE_NAME:$IMAGE_TAG