stages:
  - build
  - test
variables:
  BUILD_NAME: "computer.txt"
    
build:
  image: alpine
  stage: build
  script:
    - echo "building"
    - mkdir build
    - touch build/$BUILD_NAME
    - echo "Mainboard" >> build/$BUILD_NAME
    - cat build/$BUILD_NAME
    - echo "Keyboard" >> build/$BUILD_NAME
  artifacts:
    paths:
      - build

test:
  image: alpine
  stage: test
  script:
    - test -f build/$BUILD_NAME 
    - grep "Mainboard" build/$BUILD_NAME
    - grep "Keyboard" build/$BUILD_NAME