build:
  image: alpine
  script:
    - echo "building"
    - mkdir build
    - touch build/computer.txt
    - echo "mainboard" >> build/computer.txt
    - cat build/computer.txt
    - echo "keyboard" >> build/computer.txt

test:
  image: alpine
  script:
    - test -f build/computer.txt 