stages:
  - build
  - test

build:
  image: alpine
  stage: build
  script:
    - echo "building"
    - mkdir build
    - touch build/computer.txt
    - echo "Mainboard" >> build/computer.txt
    - cat build/computer.txt
    - echo "Keyboard" >> build/computer.txt
  artifacts:
    paths:
      - build

test:
  image: alpine
  stage: test
  script:
    - test -f build/computer.txt 
    - grep Mainboard" build/computer.txt
    - grep Keyboard" build/computer.txt