variables:
  IMAGE_NAME: claudiutulbure/cicd
  IMAGE_TAG: user-image
build:
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG