version: "3.8"
services:
  db1:
    container_name: userDB
    image: mysql
    environment:
      # Password for root access
      MYSQL_ROOT_PASSWORD: "12345678"
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - "3308:3306"
    expose:
      - "3306"
    volumes:
      - my-db:/data/mysql
  db2:
    container_name: deviceDB
    image: mysql
    environment:
      # Password for root access
      MYSQL_ROOT_PASSWORD: "12345678"
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - "3309:3307"
    expose:
      - "3307"
    volumes:
      - my-db:/data/mysql
  db3:
    container_name: monitoringDB
    image: mysql
    environment:
      # Password for root access
      MYSQL_ROOT_PASSWORD: "12345678"
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - "3310:3308"
    expose:
      - "3308"
    volumes:
      - my-db:/data/mysql
  users-app:
    container_name: usersApp
    image: user-image
    environment:
      TZ: "UTC"
      MICROSERVICE_NAME: "devicesApp"
      DB_IP: userDB
      DB_PORT: "3306"
      DB_USER: "root"
      DB_PASSWORD: "12345678"
      DB_NAME: "usermanagement"
      PORT: "8080"
      ALLOWED_ORIGINS: "http://localhost"
    ports:
      - "8080:8080"
    expose:
      - "8080"
  devices-app:
    container_name: devicesApp
    image: device-image
    environment:
      TZ: "UTC"
      DB_IP: deviceDB
      DB_PORT: "3306"
      DB_USER: "root"
      DB_PASSWORD: "12345678"
      DB_NAME: "devicemanagement"
      ALLOWED_ORIGINS: "http://localhost"
    ports:
      - "8090:8090"
    expose:
      - "8090"
  monitoring-app:
    container_name: monitoringApp
    image: monitoring-image
    environment:
      TZ: "UTC"
      DB_IP: monitoringDB
      DB_PORT: "3306"
      DB_USER: "root"
      DB_PASSWORD: "12345678"
      DB_NAME: "monitoring"
      ALLOWED_ORIGINS: "http://localhost"
    ports:
      - "8095:8095"
    expose:
      - "8095"
  frontend-app:
    container_name: frontend-user-devices-app
    image: front-end-angular
    environment:
       PORT: "80"
    ports:
      - "80:80"
    expose:
      - "80"
volumes:
  my-db: {}

networks:
  default:
    name: SD1