spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/usermanagement
    username: root
    password: 12345678

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql

device-management:
  url: http://localhost:8090/api/user

